data_ingestion:
  bucket_name: "my_bucket3924"
  bucket_file_name: "data.csv"
  train_ratio: 0.8

data_processing:
  categorical_columns:
    - "type_of_meal_plan"
    - "required_car_parking_space"
    - "room_type_reserved"
    - "market_segment_type"
    - "repeated_guest"
  numerical_columns:
    - "no_of_adults"
    - "no_of_children"
    - "no_of_weekend_nights"
    - "no_of_week_nights"
    - "lead_time"
    - "arrival_year"
    - "arrival_month"
    - "arrival_date"
    - "no_of_previous_cancellations"
    - "no_of_previous_bookings_not_canceled"
    - "avg_price_per_room"
    - "no_of_special_requests"
  target_column: "booking_status"
  skewness_threshold: 0.5
  no_of_features: 10
  test_size: 0.2
  random_state: 42

model_training:
  model_type: "RandomForestClassifier"
  hyperparameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  evaluation_metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
          